# Generated by Django 4.2.9 on 2024-01-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='articlesattachments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='attachments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='publishers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='senderpriorities',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='senders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subjectkeywordstoignore',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='textstoclearperpublisher',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
