# Generated by Django 4.2.9 on 2024-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotApp', '0002_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ispublished',
            field=models.BooleanField(blank=True, db_column='isPublished', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='articlesattachments',
            unique_together={('article_id', 'attachment_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectkeywordstoignore',
            unique_together={('keyword', 'publisher_id')},
        ),
    ]
